fixed geometry issues, updated buttons in hydrodyn GUI to be disabled when a new PDB file is loaded, finalized us_hydrodyn_results.
There are issues with Emre's code:

src/us_hydrodyn.cpp: In member function `int US_Hydrodyn::compute_asa()':
src/us_hydrodyn.cpp:486: error: cannot convert `QString*' to `float' for argument `1' to `int surfracer_main(float, std::vector<residue, std::allocator<residue> >, PDB_model*, bool)'
src/us_hydrodyn.cpp: In member function `void US_Hydrodyn::bead_check()':
src/us_hydrodyn.cpp:2380: error: cannot convert `QString*' to `float' for argument `1' to `int surfracer_main(float, std::vector<residue, std::allocator<residue> >, PDB_model*, bool)'
src/us_hydrodyn.cpp: At global scope:
src/us_hydrodyn.cpp:317: warning: 'void outward_translate_1_sphere_1_fixed(float*, float*, float*, float*, float*)' defined but not used

That need to be addressed.